### ISSUE TITLE
Trouble With the Home Button

### ISSUE THREAD

**Issue by johnhenrypezzuto** [zhaohuabing/hugo-theme-cleanwhite#1]
Hi,
Sorry I am really new to using Hugo. I noticed when I click the Home button, or the site name on the upper left corner, the link does not go anywhere (i.e., it does not go to the home page). The example website online doesn't have this issue. My blog isn't online, so that might be part of the problem. Any advice?

**Comment by zhaohuabing** [comment]
Hi @johnhenrypezzuto,
Welcome and thanks for your interest in Cleanwhite Hugo theme. I would be very happy if I can help you use it on your blog site.
I can't tell the exact problem you ran into with, both the home button and the site name just work fine on my laptop.  
Here is my suggestion: There is a fully functional example site coming along with this theme in the exampleSite dir. You can copy the content of exampleSite dir to your local Hugo project dir and start to replace and add your own content on top of it.
Before you go, you may want to get to know some basic ideas of Hugo directory structure: https://gohugo.io/getting-started/directory-structure/
Best Regards,
Huabing

**Comment by johnhenrypezzuto** [comment]
I took your advice, and have been working on that. If you get the chance, would you take a look? My issue now is that I can't get any of my categories to show up online. They work normally when I run locally on my machine.

https://johnhenryp.netlify.com/
https://github.com/johnhenrypezzuto/johnhenryp

Best,
John

**Comment by zhaohuabing** [comment]
Hi John,

The suffix of the markdown source files should be ".md".

**Comment by johnhenrypezzuto** [comment]
That worked perfectly. Thanks you very much for your time !
