### ISSUE TITLE
不好意思 請問tag要怎麼使用呀

### ISSUE THREAD

**Issue by charleyeasy** [zhaohuabing/hugo-theme-cleanwhite#102]
先感謝大大分享這麼美麗的theme!!
讓我可以輕鬆的寫自己的網頁，真的很感謝！
我想請問一下，要怎麼增加tag呢？
比方說 有
http://localhost:1313/tags/istio/
http://localhost:1313/tags/docker/
但我找不到是從哪裡建構的，不知道怎麼建構新的tag
再次感謝分享這麼美的layout！ 希望可以解決我的疑惑

**Comment by zhaohuabing** [comment]
在 post 里面设置 tag 就可以了。
