### ISSUE TITLE
How To Fix Categories , 404 page not found

### ISSUE THREAD

**Issue by desawarna** [zhaohuabing/hugo-theme-cleanwhite#11]
Thanks hugo-theme-cleanwhite work :smile: 
but when I click categories _advetorial_ , 404 page not found

Nav 
![zao](https://user-images.githubusercontent.com/1111630/47036573-f9c4ca00-d1a6-11e8-8420-fd831de98254.jpg)

404 page not found

![categprys-not-found](https://user-images.githubusercontent.com/1111630/47036733-4c9e8180-d1a7-11e8-8457-27045c2900f2.jpg)

**Comment by zhaohuabing** [comment]
Never experience this issue before. 
I can take a look into it if you could share the source files.

**Comment by desawarna** [comment]
Thank Mr @zhaohuabing , 

because I started using another template with different archetypes 😂

problem solved with change archetype,
