### ISSUE TITLE
FEATURED TAGS overlaps TOC 

### ISSUE THREAD

**Issue by eyllanesc** [zhaohuabing/hugo-theme-cleanwhite#122]
In the post https://zhaohuabing.com/post/2021-09-27-aeraki/ of the [demo site](https://zhaohuabing.com/) it is observed that FEATURED TAGS overlaps TOC:

![Screenshot_20211228_181616](https://user-images.githubusercontent.com/4896200/147614033-eb8b5be2-b38f-4e2c-b09f-5e836881a4dd.png)

**Comment by zhaohuabing** [comment]
@eyllanesc Thanks for reporting this issue. It has been fixed.
