### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by zengchengjie** [zhaohuabing/hugo-theme-cleanwhite#125]
初次使用，发现本地的代码块有高亮，发布上去后，显示的代码块没有高亮，看了您的博客，也是类似的问题并没有代码高亮，不知道是不是我配置的问题呢?
本地：
![image](https://user-images.githubusercontent.com/18211516/153119109-629a1b7a-64be-40ec-9da7-12d6ab9a9a57.png)
部署后：
![image](https://user-images.githubusercontent.com/18211516/153119164-a1823e81-973f-47b7-b028-33b468b62f47.png)

**Comment by zhaohuabing** [comment]
hugo 版本的原因，你把 netlif 的 hugo 版本设置为 0.74.1 试试
