### ISSUE TITLE
hugo serve产生了一些错误和警告

### ISSUE THREAD

**Issue by EyebrowsWhite** [zhaohuabing/hugo-theme-cleanwhite#126]
我是一个hugo新手，尝试用这个命令启动您的examlpeSite ，`hugo serve --themesDir ../..`，我可以成功启动，但是有几个错误和警告，细节如下图：
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/48169104/153122195-fd537838-8897-4102-98d3-41f1e4cf37e8.png">

这些警告似乎目前没有太大的影响，但是未来可能导致无法启动，由于我刚接触hugo，还不太会修复（虽然似乎Google的结果只需要做个替换），希望您能抽时间看一下

**Comment by zhaohuabing** [comment]
使用的一些 hugo 语法被 deprecated 了，我修改一下。
