### ISSUE TITLE
Query about table of contents not working properly for rmd files

### ISSUE THREAD

**Issue by Yijun-S** [zhaohuabing/hugo-theme-cleanwhite#129]
Hi Huabing,

First of all, thank you so much for creating this amazing Hugo template. I am a student who just started learning r programming and would like to put some of my projects on a personal website. 

While I am using the template, I noticed there is a TOC automatically generated and they work very well with markdown files. But for RMD files, the links in the table don't seem to work properly - they are not linked to the corresponding headers. Your sample RMD post also has the same issue I think.

Would there be a way to correct this? Or would there be a way to not have TOC for all the pages? I checked the settings and tutorials online but cannot seem to solve this.

My website is: https://yijuns-portfolio.netlify.app/ 

Many thanks and looking forward to your reply. 中文或英文回复都可以，不知道您偏好哪种，谢谢！

Best,
Yijun

**Comment by Yijun-S** [comment]
I can't find any other way, so I rendered the rmd file to md.

**Comment by zhaohuabing** [comment]
Hi Yijun,
You can remove TOC by adding the following line to the metadata of the md files.

```
showtoc: false
```
