### ISSUE TITLE
An error occurred: giscus is not installed on this repository

### ISSUE THREAD

**Issue by matte-brown** [zhaohuabing/hugo-theme-cleanwhite#139]
I am having trouble with [params.giscus]

below is my config and I am not clear on what is needed. Can you please help explain the first 4 params and how they should be defined. where would I find "data_category" and "data_category_id". Also do the repo items seem correct?

`data_repo="https://github.com/matte-brown/[repoName]"

  data_repo_id="XXXXXXXXX"

  data_category="your category"

  data_category_id="your category id"

  data_mapping="pathname"

  data_reactions_enabled="1"

  data_emit_metadata="0"

  data_theme="light"

  data_lang="en"

  crossorigin="anonymous"`

**Comment by DeeWooo** [comment]
data_repo="[https://github.com/matte-brown/[repoName]](https://github.com/matte-brown/%5BrepoName%5D)"
