### ISSUE TITLE
relURL instead of absURL for resources

### ISSUE THREAD

**Issue by dhrp** [zhaohuabing/hugo-theme-cleanwhite#14]
For a friendly workflow, where the site can be hosted on different domains (e.g. localhost:1313, when developing locally, localhost:32933 when in Docker, and staging.my-site.com as well as my-site.com) 

it'd be better if this template would use relURL everywhere instead of absURL.

**Comment by dhrp** [comment]
hey @zhaohuabing, thanks for fixing this already. After I had opened this issue I found two more little related issues. I now created a PR for that. Feedback, in case of necessary, welcome.

**Comment by zhaohuabing** [comment]
Thanks for the PR, it has been merged.
