### ISSUE TITLE
The theme won't show in git hub page.

### ISSUE THREAD

**Issue by yuqian-liu** [zhaohuabing/hugo-theme-cleanwhite#143]
Hi, I can have the theme running in localhost but after the static files went into github page, the style lost. Do I need some permisson?

**Comment by Weirdchun** [comment]
I have the same thing, I can preview it well locally, but when I deploy it to github page, the homepage will show the xml code directly, please how to solve it

**Comment by Weirdchun** [comment]
I also encountered this problem, did you solve it please?
