### ISSUE TITLE
Any plans for new releases (>1.0.0)

### ISSUE THREAD

**Issue by stephen-ombre** [zhaohuabing/hugo-theme-cleanwhite#145]
@zhaohuabing, Are there any plans to create newer releases/tags for a more controlled use of the this theme beyond version 1.0.0 (from Oct-2019). I'm looking for a more recent and fixed feature set that I can reliably use and have more control over my blog deployments.
It would be very helpful if we can fix the theme version with a version that is more recent than version 1.0.0.

**Comment by zhaohuabing** [comment]
The master branch is pretty stable for a while. I'll tag it as 2.0.0 and you could update to it.

**Comment by stephen-ombre** [comment]
@zhaohuabing, great and thanks :thumbsup:

**Comment by zhaohuabing** [comment]
Close this issue since 2.0.0 has been released.
