### ISSUE TITLE
Tag and category pages lead to a 404 error

### ISSUE THREAD

**Issue by iTawkins** [zhaohuabing/hugo-theme-cleanwhite#148]
I can create tags and categories just fine in my posts, but whenever I create a tag/category, its link leads to a 404 error. It's almost like the category and tag pages aren't being created.

**Comment by simonwei97** [comment]
yeah, I have same problem. If I add another categories like "Algo", its like add Algo button on left head, but when I click ALGO, it will lead to 404 page not found error. How to create categories correctly?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/119845914/222170995-adcb74d6-7bc9-46a0-a5a8-927c96ad825a.png">


```markdown
categories: [Algo]
```

**Comment by zhaohuabing** [comment]
@iTawkins @simonwei97 Thanks for reporting this issue. It should have been fixed by https://github.com/zhaohuabing/hugo-theme-cleanwhite/commit/269be4cfd1121fbebc0ef4bb833ef918b6576a3e, could you please try again?
