### ISSUE TITLE
Uncomment "ABOUT ME" sidebar title

### ISSUE THREAD

**Issue by danielashare** [zhaohuabing/hugo-theme-cleanwhite#150]
Hello,

I don't seem to have permission to create a PR. 

In `layouts/partials/side.html` on line 13, `<hr><h5><a href="{{ "/about" | relLangURL }}">ABOUT ME</a></h5>` is commented out leading to the About Me sidebar section to have no title.

Thanks for your help,
Dan

**Comment by zhaohuabing** [comment]
@danielashare Everyone should have permission to create a PR.
