### ISSUE TITLE
About toc

### ISSUE THREAD

**Issue by EMTincopa** [zhaohuabing/hugo-theme-cleanwhite#18]
Hey, How can I disable the TOC option for a post?
Please :( 
I used toc: false but does not work.

**Comment by EMTincopa** [comment]
Oh yeah. Thank you!

**Comment by EMTincopa** [comment]
Uhm, How Can I  create an image preview for every new post? Is it possible?
Something like this:
![screenshot](https://user-images.githubusercontent.com/45944562/50458472-5b38b000-0931-11e9-84ef-10fa21edc1ea.png)

**Comment by zhaohuabing** [comment]
This feature is not supported. I'd like to keep this theme clean, not too fancy.
