### ISSUE TITLE
Sidebar does not display

### ISSUE THREAD

**Issue by yeaheo** [zhaohuabing/hugo-theme-cleanwhite#19]
When I create a new site and copy the example files in the theme directory to the root directory of the site. After running, I found that the right sidebar is not displayed
![xxx](https://ws4.sinaimg.cn/large/006tNbRwly1fyegqank19j30yt0u0jt9.jpg)

**Comment by yeaheo** [comment]
I just do it according to the way you command.but it doesn't look like affect. And I tried it on other machines. Looks like it's not good.
I followed the steps below：
```bash
👍 hugo new site myblog
👍 cd myblog/themes
👍 git clone https://github.com/zhaohuabing/hugo-theme-cleanwhite.git
👍 cp -a hugo-theme-cleanwhite/exampleSite/* ..
👍 cd ..
👍 hugo server -D
```
What wrong? You can follow the above steps to get some command for me.
Thanks!!!

**Comment by zhaohuabing** [comment]
Sidebar will be hidden if the screen is not large enough to show it. Please try at a wider screen.

**Comment by yeaheo** [comment]
@zhaohuabing It doesn't look like a problem of screen. I use other computers as well. You can try it with your own computer.

**Comment by zhaohuabing** [comment]
I have tried and it works.
