### ISSUE TITLE
Redirecting the 'About Me'

### ISSUE THREAD

**Issue by johnhenrypezzuto** [zhaohuabing/hugo-theme-cleanwhite#2]
Is it possible to direct the 'About Me' in the sidebar to it's own page?

**Comment by zhaohuabing** [comment]
Yes, you can.
You can accomplish that by overriding the partial “layouts/partials/sidebar.html”

1. Copy sidebar.html to layouts/partials/sidebar.html of your website

2. Modify line 30
        <hr><h5><a href="your_about_me_pate">ABOUT ME</a></h5>

**Comment by johnhenrypezzuto** [comment]
Thank you for your help!
