### ISSUE TITLE
single.html:23: unclosed action error

### ISSUE THREAD

**Issue by pbuzdin** [zhaohuabing/hugo-theme-cleanwhite#22]
> Error: "D:\hugo\themes\hugo-theme-cleanwhite\layouts\_default\single.html:23:1": parse failed: template: _default\single.html:23: unclosed action

**Comment by linux0x5c** [comment]
The issue  #531 fix this problem.

**Comment by zhaohuabing** [comment]
It has been fixed, could you confirm and close this issue.

**Comment by pbuzdin** [comment]
I will check later.
