### ISSUE TITLE
highlight.js

### ISSUE THREAD

**Issue by linux0x5c** [zhaohuabing/hugo-theme-cleanwhite#26]
Hi @zhaohuabing  ,请问下这个主题是否支持highlight.js.现在不太清楚 header.html 如何改动。特此请教，谢谢。

**Comment by zhaohuabing** [comment]
目前不支持，看上去挺好的，欢迎提pr。

**Comment by linux0x5c** [comment]
ok,我这边已经加上了，效果如图所示。我明天提个pr。[https://s2.ax1x.com/2019/01/09/FOPRL8.png](url)

**Comment by linux0x5c** [comment]
I will pr.
