### ISSUE TITLE
how to show correct picture link for blog with sub path url.com/blog

### ISSUE THREAD

**Issue by larrycai** [zhaohuabing/hugo-theme-cleanwhite#29]
Normally in the blog post, it is written like `img/post-1.png`, but if the blog has http://url.com/blog, it has issues

Generated html is http://url.com/img/img/post-1.png, can I have setting to generate http://url.com/blog/img/post-1.png ?

workaround solution is `/img/post-1.png`, but it looks ugly.

Rgs, Larry

**Comment by gainskills** [comment]
looks like this Q is about how you managed the image. 

From my understanding, if the images were managed by Hugo, they will be saved to folder 'static/img' which will be published to '/img' folder by default. searched on Hugo, there is no option to change this way.

Or you can manage the post manually: manage the images in the folder '_hugo_/public/blog/' manually (not sure if this works for development mode)
