### ISSUE TITLE
how to tune the head menu?

### ISSUE THREAD

**Issue by larrycai** [zhaohuabing/hugo-theme-cleanwhite#30]
two questions

1. how to change the "Home" to Chinese"首页"
2. how to disable the category list shown in the head menu

![image](https://user-images.githubusercontent.com/106192/51235073-dd375a00-196e-11e9-8a24-bf88fe0f57d1.png)

the blog site is https://isoliu.gitlab.io/blog/

**Comment by zhaohuabing** [comment]
Hi larrycai,
If you need more customization than the config.toml offered, you need to override some of the templates int the theme.

In particularly, you need to override "layouts/partials/nav.html" to change the "Home" to Chinese"首页" and disable the category list shown in the head menu
