### ISSUE TITLE
may add demo site using gitlab-ci 

### ISSUE THREAD

**Issue by larrycai** [zhaohuabing/hugo-theme-cleanwhite#31]
I spend the time to make it work in gitlab, and it will be good to have documentation or demo site using `.gitlab-ci.yaml`

see sample https://gitlab.com/isoliu/blog/blob/master/.gitlab-ci.yml 

Then no knowledge mostly needed to have a sample blog in seconds,  Only need is to customize for own blog system

**Comment by zhaohuabing** [comment]
Hi Larrycai,
I don't know much about how to make it work in gitlab. If you have any suggestion, welcome to open a PR.
