### ISSUE TITLE
I'd like to set Open Graph Protocol  for each article, what should I do?

### ISSUE THREAD

**Issue by ng-yt** [zhaohuabing/hugo-theme-cleanwhite#32]
I'd like to set Open Graph Protocol  for each article, what should I do?

![2019-01-29 23 13 50](https://user-images.githubusercontent.com/35297716/51914221-ac99fa80-241b-11e9-95ac-e34e92b53c5b.png)

Thank you

**Comment by zhaohuabing** [comment]
Hi,

Check out this article:
https://vietlq.github.io/2017/04/30/access-hugo-page-variables/

You may need to add og meta to
https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/layouts/partials/head.html

A PR would be great after you verifing this approach.

Cheers,
Huabing

**Comment by ng-yt** [comment]
@zhaohuabing 
Thank you for your reply

ok!
I will verify this issue and try

**Comment by ng-yt** [comment]
Thank you merge!!
I will keep using this theme carefully
