### ISSUE TITLE
Year is not right

### ISSUE THREAD

**Issue by heyuanchao** [zhaohuabing/hugo-theme-cleanwhite#42]
When I visit https://zhaohuabing.com/page/9/, footer is ”Copyright © Huabing Blog , 2017”
When I visit https://zhaohuabing.com/page/1/, footer is ”Copyright © Huabing Blog , 2019”

**Comment by zhaohuabing** [comment]
This theme is using "Date" page variable for copyright, so the displaying
date depends on the current page.

**Comment by johnhenrypezzuto** [comment]
This causes an issue for the 404 not found page where the year goes to 0001, example: https://zhaohuabing.com/404example
