### ISSUE TITLE
How to change the header font color & image size? 

### ISSUE THREAD

**Issue by johnhenrypezzuto** [zhaohuabing/hugo-theme-cleanwhite#43]
I want to continue to customizing the theme. How do I change the color of the font in my main heading? Will this affect the header font color for posts too? How do I change the dimensions of the header? Thank you !!

**Comment by zhaohuabing** [comment]
In Hugo, layouts can live in either the project’s or the themes’ layout folders, and the most specific layout will be chosen.  So you can create a layout folder in your site source directory, copy the partials which need to be customized from the theme to the folder, and change them as you want.

Please refer to Hugo documents for more details: https://gohugo.io/templates/base/#override-the-base-template
