### ISSUE TITLE
About-me crashes when on the second page

### ISSUE THREAD

**Issue by johnhenrypezzuto** [zhaohuabing/hugo-theme-cleanwhite#44]
When you click "about me" on the sidebar and you are not on the first page (i.e. after click "older posts"), the About Me crashes. Directs to https://yoursitename/page/2/about.

I am not able to recreate this on the example site, because the About Me page doesn't direct anywhere.

Is there a way to use an absolute reference to the about me in the config.toml?

**Comment by zhaohuabing** [comment]
Hi John,

Thanks for using this theme and raise the issue.I updated the theme to link "about me" page in the sidecar. Now it doesn't support link about page to external page, if you do want to do that, you can override the sidebar.html to achieve that.

**Comment by zhaohuabing** [comment]
Wrong commit message, this is the fix for #42
