### ISSUE TITLE
Google and Baidu verification codes hard coded

### ISSUE THREAD

**Issue by evanwieren** [zhaohuabing/hugo-theme-cleanwhite#47]
In layouts/partials/head.html you have hard coded values.

<head>
    <meta name="google-site-verification" content="9vIieCe-Qpd78QOmBl63rGtIVbhY6sYyuxX3j8XWBA4" />
    <meta name="baidu-site-verification" content="LRrmH41lz7" />

These should be optional.

**Comment by zhaohuabing** [comment]
It's fixed. Thanks for pointing it out.
