### ISSUE TITLE
the date is incorrect after I used algolia .

### ISSUE THREAD

**Issue by chengpengzhao** [zhaohuabing/hugo-theme-cleanwhite#49]
The search page just likes this :    the current date shows Jan 01, 0001 and I can't figure out where the problem is.   

Jan 01, 0001
**Tags**
Jan 01, 0001

Jan 09, 2019
**Clean White Theme for Hugo**
Clean White Theme for Hugo CleanWhite is a clean, elegant, but fully functional blog theme for Hugo. Here is a live demo site using this theme. It is based on huxblog Jekyll Theme and Clean Blog Jekyll Theme. These two upstream projects have done awesome jobs to create a blog theme, what I’m doing here is porting it to Hugo, of which I like the simplicity and the much faster

**Comment by viskpan** [comment]
hi there, I am experiencing the same problem, did you manage to solve it. if so please share

**Comment by mattericbrown** [comment]
have you resolved this issue? I am having the same problem

**Comment by helloweizhang** [comment]
Becase you made a wrong date format in the Post file :
correct format: 2020-01-10
incorrect: format: 2020-1-1, 2020-01-1, 2020-1-01

中文
如果在MD文件中用了不正确的日期格式，会显示0001，而不是当前的日期，日期格式应该是年份4位，月份2位，日期2位
正确的格式：2020-01-10  
错误的格式：2020-1-1
