### ISSUE TITLE
Index.html Missing Posts

### ISSUE THREAD

**Issue by mike-ripberger** [zhaohuabing/hugo-theme-cleanwhite#51]
I used the example content and the example config.toml, but the index.html never includes any posts on the front page. The div on the front page is always empty. All of the HTML files for each posts is built and accessible via URL.

<div class="
            col-lg-8 col-lg-offset-1
            col-md-8 col-md-offset-1
            col-sm-12
            col-xs-12
            post-container
        ">
< /div>

**Comment by mike-ripberger** [comment]
Actually, changing first line in portfolio.html to following fixed it.

{{ $paginator := .Paginate (where .Pages "Type" "posts") }}

**Comment by zhaohuabing** [comment]
I have no clue why this happened, it works on my ubuntu server just fine.

**Comment by 499602D2** [comment]
Same issue, posts never appear without the fix @mike-ripberger suggested.

**Comment by grevian** [comment]
I had this same issue, it appears to be that [the hugo quickstart](https://gohugo.io/getting-started/quick-start/#step-4-add-some-content) recommends content going into a `posts/` directory, but this theme checks for a content type of `post` when doing this loop over content. It's probably tough to correct now without a lot of breakage, but might be worth a callout in the README? It's easy to miss. (Moving my `content/posts/` into `content/post/` solved the problem for me)
