### ISSUE TITLE
Issue with search

### ISSUE THREAD

**Issue by ron-kuby** [zhaohuabing/hugo-theme-cleanwhite#52]
The search page returns a strange result for a post from Dec 31, 0000. 
`
dev_and_the_dude-Web Development Blog Toggle navigation dev_and_the_dude Home Data SEARCH var $body = document.body; var $toggle = document.querySelector('.navbar-toggle'); var $navbar = document.querySelector('#huxblog_navbar'); var $collapse = document.querySelector('.navbar-collapse'); $toggle.addEventListener('click', handleMagic) function handleMagic(e){ if ($navbar.className.indexOf('in') 0) { $navbar.className = " "; setTimeout(function(){ if($navbar.className.indexOf('in') dev_and_the_dude the web abides Support Vector Machines, for Bowlers Support Vector Machine History The goal of this post is to explain how a Support Vector Machine works and how it relates to bowling.`

**Comment by ron-kuby** [comment]
This is the site I am having this trouble on

https://www.devandthedu.de/search/

**Comment by zhaohuabing** [comment]
It seems some of the css and js files are missing on your site.

**Comment by ron-kuby** [comment]
@zhaohuabing There is an issue with Chrome and Baidu serving mixed assets so chrome will not load the css. Works in Firefox. Any chance you could help me out? I can provide a link to my repo and would really appreciate any feedback. Also thanks for building this theme!

**Comment by zhaohuabing** [comment]
@ron-kuby Check line 19 of https://devandthedu.de/search/index.html 

 <link rel="stylesheet" href="s://devandthedu.de/css/iDisqus.min.css"/>

It should be 
 <link rel="stylesheet" href="https://devandthedu.de/css/iDisqus.min.css"/>
