### ISSUE TITLE
various issues on running 'hugo' command

### ISSUE THREAD

**Issue by jamestho** [zhaohuabing/hugo-theme-cleanwhite#55]
Hi,

I love the clean site theme that you created! :)
When I type in 'hugo' at the command line interface then I receive the following results:

### hugo
Building sites … WARN 2019/06/09 15:14:41 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/06/09 15:14:41 found no layout file for "HTML" for "taxonomyTerm": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/06/09 15:14:41 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2019/06/09 15:14:41 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
WARN 2019/06/09 15:14:41 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}.
WARN 2019/06/09 15:14:43 Page's .UniqueID is deprecated and will be removed in a future release. Use .File.UniqueID.
WARN 2019/06/09 15:14:43 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
WARN 2019/06/09 15:14:43 Page's .Dir is deprecated and will be removed in a future release. Use .File.Dir.
WARN 2019/06/09 15:14:43 .File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}

Is this something that I've done wrong please?
Many thanks!
James

**Comment by gainskills** [comment]
since all log are WARN instead of ERR, you site should be accessible, right?

**Comment by jamestho** [comment]
yes, the site is accessible but thought it would be good for you to know that some items will be deprecated at a future release. 
I've got everything to work so far, except for the tag on the sidebar, but I'm sure that I can figure it out :)

**Comment by gainskills** [comment]
Here is my version: https://github.com/gainskills/hugo-theme-cleanwhite/blob/master/layouts/partials/sidebar.html for reference. 

I did too much change to push them back to the master version.

**Comment by jamestho** [comment]
thanks, for your updated sidebar it was useful - i replaced the one that I had! :) However, I can still only see the 'about me' link on my sidebar!  I have checked my config.toml, and I think that I have the right settings in there, so I guess it must be something quite basic!

I have uploaded my config.toml to be here: https://github.com/jamestho/chilli-blog
Can you see what I'm doing wrong, please?

Many thanks for your help so far! :)

**Comment by gainskills** [comment]
I'm afraid I can't go through your file now, share my configuration file with you https://github.com/gainskills/Kex-Zh-Blog/blob/master/config.toml
