### ISSUE TITLE
Duplicated scroll bar and stuck scrolling

### ISSUE THREAD

**Issue by QiKatherine** [zhaohuabing/hugo-theme-cleanwhite#60]
Thank you for creating this awesome theme and I really enjoying using it!

I was told that the scrolling control in my article page is not very smooth: it got stuck occasionally when scrolling very quickly.

I checked and found it's caused by the duplicated scroll bar, which only happened when setting `friends=false` in `cofig.toml`. Change `friends=true` will fix the issue.

![image](https://user-images.githubusercontent.com/20196556/65823610-55218800-e251-11e9-92da-d377347c2ea2.png)

**Comment by zhaohuabing** [comment]
Thanks for rasing this issue. 
This does happen on my blog as well. I'm trying to figure out the reason.  I suggest keeping the friend option true before it's fixed.

**Comment by zhaohuabing** [comment]
It should be fixed now @QiKatherine

**Comment by QiKatherine** [comment]
Thanks. Pure gold! 👍
