### ISSUE TITLE
issue about deploying github.io website

### ISSUE THREAD

**Issue by RainFung** [zhaohuabing/hugo-theme-cleanwhite#62]
Hello Author, I have seen your theme recently and I like it very much, but I have encountered some problems when using your theme. I hope I can get your guidance.

1. First, i use `quick start` method in demo.
```bash
$ mkdir test
$ cd test
$ mkdir themes
$ cd themes
$ git clone https://github.com/zhaohuabing/hugo-theme-cleanwhite.git
$ cp -r hugo-theme-cleanwhite/exampleSite/** ../
$ cd ..
$ hugo serve
```

2. I only modify the base url in  `config.toml` in `themes`.
`baseurl = "http://fengrain.github.io"`

3. `hugo server -D`, then push `public` to my repo https://github.com/RainFung/fengrain.github.io.

Finally, 
http://fengrain.github.io/ raise 404 error.
https://rainfung.github.io/fengrain.github.io/ only shows text.

If it's convenient, we'd like to contact you by Wechat. My Wechat ID is 409908131. Thanks.

**Comment by RainFung** [comment]
Sorry to bother you in github and e-mail. I hava solved it by rename repo name `fengrain.github.io` to my github name `rainfung.github.io`. Thanks your excellenct work.

**Comment by zhaohuabing** [comment]
It's good to hear that you figured it out, enjoy!

**Comment by helloweizhang** [comment]
Accessing github in China is very slow, I suggest you migrate to netlify and use freenom and dnspod for domain forwarding
