### ISSUE TITLE
disqus display issue

### ISSUE THREAD

**Issue by AlexsanderShaw** [zhaohuabing/hugo-theme-cleanwhite#64]
i dont know why disqus's display is different from yours, i didn't do anything...
and here is my [blog](https://alexsandershaw.github.io/)

**Comment by zhaohuabing** [comment]
I may help if you could share the source files of your blog

**Comment by helloweizhang** [comment]
disqus 有两个界面，VPN翻墙模式下是用原生界面，如果是国内直连访问的情况下是用disqus-php-api转发的界面

Disqus module has two UI, if you visit by VPN on china, it shows Disqus UI , if you visit direct it will show disqus-php-api UI.
