### ISSUE TITLE
How can i change various theme icon in theme?

### ISSUE THREAD

**Issue by RainFung** [zhaohuabing/hugo-theme-cleanwhite#65]
Hello, How can i change various icon or picture in the theme?

1. icon
![image](https://user-images.githubusercontent.com/23121539/67851738-057ef680-fb46-11e9-819e-4ef58c81bb20.png)

2. sidebar
![image](https://user-images.githubusercontent.com/23121539/67851760-13347c00-fb46-11e9-9e07-ba0472b1f2f0.png)

3.article sidebar

**Comment by zhaohuabing** [comment]
Replace the pictures in staic/img folder with your own.
