### ISSUE TITLE
How to use View counter outside China 

### ISSUE THREAD

**Issue by VaibhavSingh033** [zhaohuabing/hugo-theme-cleanwhite#66]
In the config.toml I see there is a provision for the code to display view counter, however I have not been able to use this feature. As per comments, it says use leancloud, I made an account there but the website is simply non usable outside CN. any other way to get this counter working ??

  # leancloud storage for page view counter
  page_view_conter = true 
  leancloud_app_id = ""
  leancloud_app_key = ""

**Comment by zhaohuabing** [comment]
Leancloud is available outside China. It even has an English version of web site.
