### ISSUE TITLE
How to remove TOC from markdown generated 

### ISSUE THREAD

**Issue by VaibhavSingh033** [zhaohuabing/hugo-theme-cleanwhite#67]
So, this must be pretty basic but I have tried everything. Added toc: false in header removed it everything but this TOC which gets generated in the output doesnt go away. 

Please see yellow highlighted in attached image
![Capture1](https://user-images.githubusercontent.com/19756890/69006583-fe822180-0956-11ea-8dcf-0f4a25dd515a.JPG)

Please assist on how to remove that TOC

**Comment by merikan** [comment]
standard behavior is that a TOC is created for all pages. if you want to change this then
add 'showtoc: false' as a sitewide param in config.toml see #45
If you only want to change for a specific page, add 'showtoc: false' as a front matter

**Comment by helloweizhang** [comment]
TOC module in the file: ` hugo-theme-cleanwhite-master/layouts/_default/single.html`
You can edit it by yourself.
