### ISSUE TITLE
How to change 

### ISSUE THREAD

**Issue by EMTincopa** [zhaohuabing/hugo-theme-cleanwhite#69]
Hi!
I want to change standard font of all pages. How?  Is there an easy option adding something as a sitewide param in config.toml? please help :(

**Comment by zhaohuabing** [comment]
You can customize the font by customizing the css.

**Comment by merikan** [comment]
@EMTincopa 
You have the option to override css and js by providing your own custom ones #59

To override styling with a custom css:
1. create your custom css file in folder `static/css`
`$ vim static/css/custom.css`
2. Add your custom css styling i.e.
```
body {
  font-family: Century Gothic,CenturyGothic,AppleGothic,sans-serif; 
}
``` 
3. Update your configuration to enable the custom css file. Open `config.toml` and add the following:
`  custom_css = ["css/custom.css"]`
4. Refresh your browser

**Comment by EMTincopa** [comment]
Thank you!!!
