### ISSUE TITLE
search page 404

### ISSUE THREAD

**Issue by naah69** [zhaohuabing/hugo-theme-cleanwhite#7]
i had configuration algolia's config ,but when i click search on web,it go to 404 page

**Comment by naah69** [comment]
it need copy exampleSite/content/search to your content

**Comment by mattericbrown** [comment]
@naah69 How did you get the files to copy into your content folder? I am running into the same issue you did.

**Comment by naah69** [comment]
copy exampleSite/content/search to your content folder

**Comment by ron-kuby** [comment]
@naah69 thank you that seems to fix the 404 issue but there is still some problem with the results and it changes the date to 0001 for some reason
