### ISSUE TITLE
How to create a photo gallery.

### ISSUE THREAD

**Issue by EMTincopa** [zhaohuabing/hugo-theme-cleanwhite#70]
I like the way you manage this photo gallery: https://zhaohuabing.com/post/2019-10-08-amsterdam/
I want to create my own photo gallery, Can you explain me how did you create Amsterdam's gallery photo? (code? example site post example?)
Please, thank you very much!

**Comment by lynxrv21** [comment]
Hi @EMTincopa, I'm working on setting up a blog using cleanwhite theme too.
There is [hugo-easy-gallery](https://github.com/liwenyip/hugo-easy-gallery) shortcodes integrated, so you can look into its [demo](https://www.liwen.id.au/heg/)
Shortly, you can do it by adding a single line:
`{{< gallery dir="/img/arduino" />}} {{< load-photoswipe >}}`

**Comment by zhaohuabing** [comment]
@lynxrv21 is right
@EMTincopa below is the source code of this page https://zhaohuabing.com/post/2019-10-08-amsterdam/
https://github.com/zhaohuabing/hugo_blog/blob/master/content/post/2019-10-08-amsterdam.md
