### ISSUE TITLE
How to replace categories?

### ISSUE THREAD

**Issue by shanyit** [zhaohuabing/hugo-theme-cleanwhite#71]
This theme is so great. But I want to replace Tech, Life with other names. How to do that.  I can not find any button to change those defined in this theme.

**Comment by helloweizhang** [comment]
中文教程：[Tech]菜单目录是根据post文件夹里面的md文件自动生成的 ，你打开exampleSite中的post其中一个md文件，里面有categories: [ Tech ]，将这句删除，或者将tech改成你自己想要的分类目录

Yes，You can edit or delete the **categories: [ Tech ]**
`Path: hugo-theme-cleanwhite-master/exampleSite/content/post`
Example, move all the file of post folder to desktop, only leave 2018-01-02-nginmesh-install.md, open it by Notepad or Sumlime text ,find this : categories: [ Tech ]

**Comment by shanyit** [comment]
Thanks so much！ I see it.




| |
shanyit
|
|
shanyit@163.com
|
签名由网易邮箱大师定制


On 01/12/2020 10:07，Lalajoy<notifications@github.com> wrote：

中文教程：[Tech]菜单目录是根据post文件夹里面的md文件自动生成的 ，你打开exampleSite中的post其中一个md文件，里面有categories: [ Tech ]，将这句删除，或者将tech改成你自己想要的分类目录

Yes，You can edit or delete the categories: [ Tech ]
Path: hugo-theme-cleanwhite-master/exampleSite/content/post
Example, move all the file of post folder to desktop, only leave 2018-01-02-nginmesh-install.md, open it by Notepad or Sumlime text ,find this : categories: [ Tech ]
