### ISSUE TITLE
请问怎样配置disqus-php-api

### ISSUE THREAD

**Issue by helloweizhang** [zhaohuabing/hugo-theme-cleanwhite#72]
您好，由于README.MD的教程写得比较简单，试过很多种方法也没有成功配置disqus-php-api，以下是我的配置方法，请问问题出在哪里呢？

### 说明
mycompanyvps.com    是我用来存放disqus-php-api的网站
mynetlifyblog.com       是我用于存放hugo生产的静态文件的网站

### 现在的情况
a.成功：在翻墙的情况下，成功访问disqus
b.失败：没有翻墙的情况下，无法访问disqus

### Disqus的api设置
> 这里我用了我Blog的网站地址，不清楚这里用Blog的网站，还是VPS的网站地址

【疑问1】: Settings/Domains: `mynetlifyblog.com`

Authentication/Default Access: Read,Wtite,and Manage Forums
Callback URL: https://mycompanyvps.com/disqus/api/login.php

### config.toml的参数设置
> 我看到官方教程有这个参数，但是您的config.toml文件没有提到这个参数

 【疑问2】: forum = "这里填什么"  

>我一直认为我的问题应该是出在疑问3这个地方，disqus_proxy我不清楚是怎样设置，我看到有的教程这里用二级域名，我没有二级域名，直接用目录表示

【疑问3】:   disqus_proxy = "https://mycompanyvps.com/disqus"  
  disqus_site = "https://mynetlifyblog.com"

**Comment by zhaohuabing** [comment]
直接用curl或浏览器试一下能否访问你的代理URL，如果有问题，查一下你的web服务器及相应的php插件是否运行正常

**Comment by EagleYing** [comment]
> 您好，由于README.MD的教程写得比较简单，试过很多种方法也没有成功配置disqus-php-api，以下是我的配置方法，请问问题出在哪里呢？
> 
> ### 说明
> mycompanyvps.com 是我用来存放disqus-php-api的网站
> mynetlifyblog.com 是我用于存放hugo生产的静态文件的网站
> 
> ### 现在的情况
> a.成功：在翻墙的情况下，成功访问disqus
> b.失败：没有翻墙的情况下，无法访问disqus
> 
> ### Disqus的api设置
> > 这里我用了我Blog的网站地址，不清楚这里用Blog的网站，还是VPS的网站地址
> 
> 【疑问1】: Settings/Domains: `mynetlifyblog.com`
> 
> Authentication/Default Access: Read,Wtite,and Manage Forums
> Callback URL: https://mycompanyvps.com/disqus/api/login.php
> 
> ### config.toml的参数设置
> > 我看到官方教程有这个参数，但是您的config.toml文件没有提到这个参数
> 
> 【疑问2】: forum = "这里填什么"
> 
> > 我一直认为我的问题应该是出在疑问3这个地方，disqus_proxy我不清楚是怎样设置，我看到有的教程这里用二级域名，我没有二级域名，直接用目录表示
> 
> 【疑问3】: disqus_proxy = "https://mycompanyvps.com/disqus"
> disqus_site = "https://mynetlifyblog.com"

我和您遇到了同样的情况，请问解决了吗？

**Comment by helloweizhang** [comment]
> > 您好，由于README.MD的教程写得比较简单，试过很多种方法也没有成功配置disqus-php-api，以下是我的配置方法，请问问题出在哪里呢？
> > ### 说明
> > mycompanyvps.com 是我用来存放disqus-php-api的网站
> > mynetlifyblog.com 是我用于存放hugo生产的静态文件的网站
> > ### 现在的情况
> > a.成功：在翻墙的情况下，成功访问disqus
> > b.失败：没有翻墙的情况下，无法访问disqus
> > ### Disqus的api设置
> > > 这里我用了我Blog的网站地址，不清楚这里用Blog的网站，还是VPS的网站地址
> > 
> > 
> > 【疑问1】: Settings/Domains: `mynetlifyblog.com`
> > Authentication/Default Access: Read,Wtite,and Manage Forums
> > Callback URL: https://mycompanyvps.com/disqus/api/login.php
> > ### config.toml的参数设置
> > > 我看到官方教程有这个参数，但是您的config.toml文件没有提到这个参数
> > 
> > 
> > 【疑问2】: forum = "这里填什么"
> > > 我一直认为我的问题应该是出在疑问3这个地方，disqus_proxy我不清楚是怎样设置，我看到有的教程这里用二级域名，我没有二级域名，直接用目录表示
> > 
> > 
> > 【疑问3】: disqus_proxy = "https://mycompanyvps.com/disqus"
> > disqus_site = "https://mynetlifyblog.com"
> 
> 我和您遇到了同样的情况，请问解决了吗？

解决了。disqus-php-api的bug
如果主题没有回复，就会有以上的错误。
所以每次发布新的文章之后，需要手动提前回复一下文章，才会显示disqus
