### ISSUE TITLE
How to integrate with nginx

### ISSUE THREAD

**Issue by lanceleedev** [zhaohuabing/hugo-theme-cleanwhite#75]
I use nginx to reverse proxy 1313 port，but artical url is domain:1313,  i hope that url don't display port, like this : http:domain/post/

**Comment by lynxrv21** [comment]
No need to point nginx to hugo server, just use `hugo -D` command to [build static pages](https://gohugo.io/getting-started/quick-start/#step-7-build-static-pages) and then configure nginx to serve static files. You can see one of guides for details: [one](https://medium.com/@jasonrigden/how-to-host-a-static-website-with-nginx-8b2dd0c5b301) and [two](https://medium.com/@jgefroh/a-guide-to-using-nginx-for-static-websites-d96a9d034940).
