### ISSUE TITLE
关于博客日期的问题

### ISSUE THREAD

**Issue by yiguan1573** [zhaohuabing/hugo-theme-cleanwhite#78]
你好，我发现博客的日期大于等于2020年markdown文件就不会在博客中显示出来，其他日期都可以显示出来
![QQ截图20200204230738.png](http://ww1.sinaimg.cn/large/006QQPIfly1gbkrtdnwryj31ev0luqfc.jpg)
![QQ截图20200204230713.png](http://ww1.sinaimg.cn/large/006QQPIfly1gbkrtnqxzmj31sw0vcdw0.jpg)

**Comment by zhaohuabing** [comment]
不能超过当前实际的真实日期，你试试2020-02-05。

**Comment by yiguan1573** [comment]
......原来是这样   非常感谢
