### ISSUE TITLE
bash代码块中显示异常

### ISSUE THREAD

**Issue by hzde0128** [zhaohuabing/hugo-theme-cleanwhite#79]
代码块cat > <<EOF显示在一行中，另外bash脚本解释器那块也显示不对，
![image](https://user-images.githubusercontent.com/26091808/74821057-fb277900-533d-11ea-8b00-409cf08c6f46.png)

![image](https://user-images.githubusercontent.com/26091808/74821145-201bec00-533e-11ea-938e-68fa50b0b7e3.png)
预期是这样子的：
![image](https://user-images.githubusercontent.com/26091808/74821482-a7695f80-533e-11ea-8770-d7b7aa897023.png)

![image](https://user-images.githubusercontent.com/26091808/74821355-6d985900-533e-11ea-9100-54c6d9daf13e.png)

**Comment by gainskills** [comment]
can you share your md file? At least share the md content related to the bash code.

**Comment by hzde0128** [comment]
eg:

```bash
cat > /usr/lib/systemd/system/logstash.service <<EOF
[Unit]
Description=logstash

[Service]
Type=simple
User=logstash
Group=logstash
EnvironmentFile=-/etc/default/logstash
EnvironmentFile=-/etc/sysconfig/logstash
ExecStart=/usr/local/logstash/bin/logstash "--path.settings" "/usr/local/logstash/config"
Restart=always
WorkingDirectory=/
Nice=19
LimitNOFILE=16384

[Install]
WantedBy=multi-user.target
EOF
```

btw:
   the theme has blackblock when using bash
![image](https://user-images.githubusercontent.com/26091808/75085601-df062080-5565-11ea-895e-31d9a803c04b.png)

**Comment by hzde0128** [comment]
'```bash'

**Comment by gainskills** [comment]
Checked[ my way to high light bash code](https://blog.gainskills.top/2013/11/05/make-error-usrbinld-cannot-find-luuid/#undefined). (I know  ```_language_  was mentioned in markdown official document), but I highlight the code by 
`~~~bash`
can you try it once?

![image](https://user-images.githubusercontent.com/1937472/75087571-f7e2f600-55a6-11ea-9ec1-135e94bfedbf.png)

Another thing is, please pay attention to the indent

**Comment by hzde0128** [comment]
> Checked[ my way to high light bash code](https://blog.gainskills.top/2013/11/05/make-error-usrbinld-cannot-find-luuid/#undefined). (I know ```_language_ was mentioned in markdown official document), but I highlight the code by
> `~~~bash`


> can you try it once?
> 
> ![image](https://user-images.githubusercontent.com/1937472/75087571-f7e2f600-55a6-11ea-9ec1-135e94bfedbf.png)
> 
> Another thing is, please pay attention to the indent

I tried `~~~bash`,but it didn't work,here is my markdown file:
[ELKStack671-deploy.zip](https://github.com/zhaohuabing/hugo-theme-cleanwhite/files/4238943/ELKStack671-deploy.zip)

**Comment by gainskills** [comment]
It works on my end.
![image](https://user-images.githubusercontent.com/1937472/75090023-8c5b5180-55c3-11ea-9307-27c8f0012f8a.png)

**Comment by hzde0128** [comment]
hugo version's problem? my hugo version is *v0.65.1*:

```bash
hugo version
Hugo Static Site Generator v0.65.1-6BE6684CC linux/amd64 BuildDate: 2020-02-20T14:02:42Z
```

**Comment by hzde0128** [comment]
when i use ````` instead of `````,it work fine.

![image](https://user-images.githubusercontent.com/26091808/75090793-86547900-55a1-11ea-8170-8d383a1e44b0.png)

![image](https://user-images.githubusercontent.com/26091808/75090807-b00da000-55a1-11ea-808b-b48f6e801fd3.png)

**Comment by zhaohuabing** [comment]
CSS之间有些冲突，已经把highlight的css去掉了。使用Hugo自带的代码高亮就可以，如果缺省的深色主题不喜欢，可以在config.toml中更改主题。
