### ISSUE TITLE
RSS图标显示异常

### ISSUE THREAD

**Issue by memory7734** [zhaohuabing/hugo-theme-cleanwhite#83]
将以下目录中的fa-rss替换为fa-feed可以恢复显示
themes/hugo-theme-cleanwhite/layouts/partials/sidebar.html
themes/hugo-theme-cleanwhite/layouts/partials/footer.html

**Comment by zhaohuabing** [comment]
什么问题，我网站上显示是正常的呢

**Comment by memory7734** [comment]
RSS订阅的图标是不显示的，我用了各种浏览器都不显示，我以为都看不到呢
![image](https://user-images.githubusercontent.com/13341119/76188082-251fdd00-6212-11ea-9f37-c7187b22f45b.png)

**Comment by zhaohuabing** [comment]
奇怪了，我电脑和手机上盖图标显示都是正常的呢。

**Comment by memory7734** [comment]
好吧，我找了半天也没找到原因，手机上可以正常显示，电脑各个浏览器都不行。
