### ISSUE TITLE
Add instruction how to use Japanese fonts

### ISSUE THREAD

**Issue by mshr-h** [zhaohuabing/hugo-theme-cleanwhite#86]
Clean White theme uses Chinese fonts by default.
But Japanese contents usually use Japanese fonts.
It looks really weird when rendering Japanese contents using Chinese font.
Adding some instructions how to properly render Japanese is helpful for many Japanese users.
Can I add it?
If it's ok, I'll send a PR.

**Comment by zhaohuabing** [comment]
Sure, that would be great.
