### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by EagleYing** [zhaohuabing/hugo-theme-cleanwhite#88]
I point my username.github.io to a domestic server and set my disqus-php-api on another oversea server but it did not work:

'''Access to XMLHttpRequest at 'https://disqus.my-over-seaserver.com/user.php' from origin 'https://blog.my-domestic-server.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.'''

How can I fix it?

**Comment by zhaohuabing** [comment]
Try to put them under the same parent domain. For example, if your blog is at https://blog.my-domestic-server.com,put your disqus api at https://disqus api.my-domestic-server.com. Just the domain name, the real location of your disqus can still be overseas.

**Comment by EagleYing** [comment]
Thanks the error solved, but a new error :
![image](https://user-images.githubusercontent.com/25764206/95676874-f88ed200-0bf3-11eb-9bc5-89b342fc176f.png)
I have no idea about this
