### ISSUE TITLE
fa-wechat icon displays not normally, “fa-weixin” is normal

### ISSUE THREAD

**Issue by jackbai233** [zhaohuabing/hugo-theme-cleanwhite#96]
Hi, thanks for your elegant and clean theme. When i config  the wechat in the config.toml. 
The WeChat icon is not displayed normally on the homepage. So i replace the fa-weichat with fa-weixin in the layouts\partials\footer.html , it solves my problem.

**Comment by qcneverrepeat** [comment]
The same change "fa-wechat"-"fa weixin" is also needed in layouts\partials\sidebar.html
