### ISSUE TITLE
How to change menu items? 

### ISSUE THREAD

**Issue by anthonychen118** [zhaohuabing/hugo-theme-cleanwhite#98]
Hi Thanks for the beautiful theme. I don't find how to modify menu items. For example, how to replace "GOLANG" in your theme with something else? Thanks!

**Comment by zhaohuabing** [comment]
You can modify the menu item in the config.toml of your site.
For example:
https://github.com/zhaohuabing/hugo_blog/blob/master/config.toml

**Comment by anthonychen118** [comment]
Yes I was looking at the same file. But in that file, there is no section for changing existing menu. I know how to add additional menus under [[params.addtional_menus]] though. Could you tell me how to change existing menu items?
